//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul183.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeID { get; set; }

        [DisplayName("Name")]
        //[StringLength(20, MinimumLength = 2, ErrorMessage = "Bitte geben Sie einen gültigen Namen ein")]
        //[Required(ErrorMessage = "Eingabe notwendig")]
        public string Name { get; set; }

        [DisplayName("Rang")]
        //[StringLength(20, MinimumLength = 5, ErrorMessage = "Bitte geben Sie einen gültigen Rang ein")]
        //[Required(ErrorMessage = "Eingabe notwendig")]
        public string Position { get; set; }

        [DisplayName("Standort")]
        //[StringLength(20, MinimumLength = 5, ErrorMessage = "Bitte geben Sie einen gültigen Standort ein")]
        //[Required(ErrorMessage = "Eingabe notwendig")]
        public string Office { get; set; }

        [DisplayName("Alter")]
        //[Range(18, 99)]
        //[Required(ErrorMessage = "Eingabe notwendig")]
        public Nullable<int> Age { get; set; }

        [DisplayName("Lohn")]
        //[Required(ErrorMessage = "Eingabe notwendig")]
        public Nullable<int> Salary { get; set; }
    }
}
