//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul183.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Eingabe notwendig")]
        public string UserName { get; set; }
        [DisplayName("Passwort")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Eingabe notwendig")]
        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
